# Build on previous image -- REQUIRED --
ARG PREVIOUS_IMAGE=ubuntu:latest
FROM ${PREVIOUS_IMAGE}

# Create a user with the same UID and GID as the host
ARG USER_ID=1000
ARG GROUP_ID=1000
ARG USER_NAME=maximecapelle

RUN groupadd -g ${GROUP_ID} usergroup && \
    useradd -m -u ${USER_ID} -g usergroup -s /bin/bash ${USER_NAME} && \
    usermod -aG sudo ${USER_NAME} && \
    echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# USER ${USER_NAME}
ENV SUDO_ALLOW="true"



