#### SETTING UP UBUNTU ####
ARG UBUNTU_VERSION=22.04
FROM ubuntu:$UBUNTU_VERSION

# Set non-interactive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install some basic utilities
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    curl \
    wget \
    git \
    vim \
    unzip \
    software-properties-common && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Define a default command (can be overridden)
CMD [ "bash" ]
