build_order:
  - ubuntu
  - ros2
  - px4
  - user
builds:
    #**** FIRST & LAST LAYERS ****
  - name: ubuntu
    dockerfile: Dockerfile.ubuntu
    build_args:
      - UBUNTU_VERSION=22.04
  - name: user
    dockerfile: Dockerfile.user
    build_args: []
    #*****************************
  
    #**** ROS DOCKER FILES ****
  - name: ros1
    dockerfile: Dockerfile.ros1
    build_args:
      - ROS_VERSION_=1
      - ROS_DISTRO_=noetic
  
  - name: ros2
    dockerfile: Dockerfile.ros2
    build_args:
    - ROS_VERSION_=2
    - ROS_DISTRO_=humble
    #***************************

    #**** Simulators ****
  - name: legacy_gazebo
    dockerfile: Dockerfile.legacy_gazebo
    build_args:
    - GAZEBO_VERSION=9
  
  - name: gz_sim
    dockerfile: Dockerfile.gz_sim
    build_args:
    - GAZEBO_VERSION=garden
    #***************************

    #**** Flight Software ****
  - name: px4
    dockerfile: Dockerfile.px4
    build_args: []
  
  - name: ardupilot
    dockerfile: Dockerfile.ardupilot
    build_args: []
    #***************************
