build_order:
  - ubuntu
  - ros2
  - user
builds:
  - name: ubuntu
    dockerfile: Dockerfile.ubuntu
    build_args:
      - UBUNTU_VERSION=22.04
  
  - name: ros1
    dockerfile: Dockerfile.ros1
    build_args:
      - ROS_VERSION_=1
      - ROS_DISTRO_=noetic
  
  - name: ros2
    dockerfile: Dockerfile.ros2
    build_args:
    - ROS_VERSION_=2
    - ROS_DISTRO_=humble

  - name: user
    dockerfile: Dockerfile.user
    build_args:
    - ENTRYPOINT_PATH: default_entrypoint.sh

launch:
  - IMAGE_NAME: ubuntu.ros2.user
  - WS_DIRECTORY_LOCAL: ros2_ws
  - WS_DIRECTORY_CONTAINER: /ros2_ws/
  - ENTRYPOINT_PATH: /scripts/default_entrypoint.sh
